LEETCODE_PROBLEMS = {
    "132 Pattern": "https://leetcode.com/problems/132-pattern/",
    "3Sum": "https://leetcode.com/problems/3sum/",
    "All Paths from Source to Target": "https://leetcode.com/problems/all-paths-from-source-to-target/",
    "Binary Tree Maximum Path Sum": "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    "Clone Graph": "https://leetcode.com/problems/clone-graph/",
    "Coin Change": "https://leetcode.com/problems/coin-change/",
    "Combination Sum II": "https://leetcode.com/problems/combination-sum-ii/",
    "Course Schedule": "https://leetcode.com/problems/course-schedule/",
    "Daily Temperatures": "https://leetcode.com/problems/daily-temperatures/",
    "Design Autocomplete System": "https://leetcode.com/problems/design-search-autocomplete-system/",
    "Design LRU Cache": "https://leetcode.com/problems/lru-cache/",
    "Design Search Suggestions System": "https://leetcode.com/problems/search-suggestions-system/",
    "Design Twitter": "https://leetcode.com/problems/design-twitter/",
    "Edit Distance": "https://leetcode.com/problems/edit-distance/",
    "Find Median from Data Stream": "https://leetcode.com/problems/find-median-from-data-stream/",
    "Find Minimum in Rotated Sorted Array": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    "Group Anagrams": "https://leetcode.com/problems/group-anagrams/",
    "House Robber II": "https://leetcode.com/problems/house-robber-ii/",
    "Implement Trie": "https://leetcode.com/problems/implement-trie-prefix-tree/",
    "Insert Delete GetRandom O(1)": "https://leetcode.com/problems/insert-delete-getrandom-o1/",
    "Jump Game II": "https://leetcode.com/problems/jump-game-ii/",
    "Kth Largest in Array": "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    "LRU Cache": "https://leetcode.com/problems/lru-cache/",
    "Largest Rectangle in Histogram": "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    "Letter Combinations of Phone Number": "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    "Longest Palindromic Substring": "https://leetcode.com/problems/longest-palindromic-substring/",
    "Longest Repeating Character Replacement": "https://leetcode.com/problems/longest-repeating-character-replacement/",
    "Longest Substring Without Repeating Characters": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    "Longest Word in Dictionary": "https://leetcode.com/problems/longest-word-in-dictionary/",
    "Lowest Common Ancestor of BT": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
    "Maximal Square": "https://leetcode.com/problems/maximal-square/",
    "Maximum Product Subarray": "https://leetcode.com/problems/maximum-product-subarray/",
    "Median of Two Sorted Arrays": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    "Meeting Rooms II": "https://leetcode.com/problems/meeting-rooms-ii/",
    "Merge Intervals": "https://leetcode.com/problems/merge-intervals/",
    "Merge K Sorted Lists": "https://leetcode.com/problems/merge-k-sorted-lists/",
    "Minimum Size Subarray Sum": "https://leetcode.com/problems/minimum-size-subarray-sum/",
    "Minimum Spanning Tree (Prim’s / Kruskal’s idea)": "https://leetcode.com/problems/connecting-cities-with-minimum-cost/",
    "N-Queens": "https://leetcode.com/problems/n-queens/",
    "Non-overlapping Intervals": "https://leetcode.com/problems/non-overlapping-intervals/",
    "Number of Islands": "https://leetcode.com/problems/number-of-islands/",
    "Palindrome Pairs": "https://leetcode.com/problems/palindrome-pairs/",
    "Partition Equal Subset Sum": "https://leetcode.com/problems/partition-equal-subset-sum/",
    "Reconstruct Itinerary": "https://leetcode.com/problems/reconstruct-itinerary/",
    "Reverse Nodes in k-Group": "https://leetcode.com/problems/reverse-nodes-in-k-group/",
    "Search in Rotated Sorted Array": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    "Serialize and Deserialize Binary Tree": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    "Sliding Window Maximum": "https://leetcode.com/problems/sliding-window-maximum/",
    "Subarray Sum Equals K": "https://leetcode.com/problems/subarray-sum-equals-k/",
    "Top K Frequent Elements": "https://leetcode.com/problems/top-k-frequent-elements/",
    "Valid Sudoku": "https://leetcode.com/problems/valid-sudoku/",
    "Word Ladder II": "https://leetcode.com/problems/word-ladder-ii/",
    "Word Search": "https://leetcode.com/problems/word-search/"
}
